kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: kafka-ca1
spec:
  type: NodePort
  selector:
    app: kafka-manager
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
  namespace: kafka-ca1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
        - name: kafka-manager
          image: hlebalbau/kafka-manager:3.0.0.4
          ports:
            - containerPort: 9000
          env:
            - name: ZK_HOSTS
              value: 'zookeeper-service:2181'
            - name: APPLICATION_SECRET
              value: 'random-secret'
