# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  install_dependencies:
    docker:
      # https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/node/images
      - image: circleci/node:12.3.1-stretch

    working_directory: ~/talus

    steps:
      - checkout

      # Download and cache dependencies
      # https://circleci.com/docs/2.0/caching/#yarn-node
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - run: yarn install

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: .
          paths: .

  unit_test:
    docker:
      - image: circleci/node:12.3.1-stretch-browsers

    working_directory: ~/talus

    steps:
      - attach_workspace:
          at: ~/talus

      - run: yarn test:editor:ci

      - store_artifacts:
          path: /coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies

      - unit_test:
          requires:
            - install_dependencies
